### USER APIs 

### Get all users
GET http://localhost:4000/user-api/users

### Get user by ID
GET http://localhost:4000/user-api/users/ID_HERE

### Create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "username": "Phani",
  "password": "123456",
  "email": "phani@gmail.com",
  "age": 19
}

### Login
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
  "email": "phani@gmail.com",
  "password": "123456"
}

### Update user
PUT http://localhost:4000/user-api/users/ID_HERE
Content-Type: application/json

{
  "username": "UpdatedName"
}

### Delete user
DELETE http://localhost:4000/user-api/users/ID_HERE


###  PRODUCT APIs 

### Create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
  "productId": 101,
  "productName": "SamsungGalaxyS24",
  "price": 30000,
  "brandName": "Samsung"
}

### Get all products
GET http://localhost:4000/product-api/products

### Get product by ID
GET http://localhost:4000/product-api/products/101

### Update product
PUT http://localhost:4000/product-api/products/101
Content-Type: application/json

{
  "price": 35000
}

### Delete product
DELETE http://localhost:4000/product-api/products/101
